=== emospy/HR/XMLLabels/HRLabels/DTDDoc.dtd
<!ELEMENT Labels_Description (product)>
<!ELEMENT product (product_name, version, client_name, forms)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT client_name (#PCDATA)>
<!ELEMENT forms (form+)>
<!ELEMENT form (formname, description, header, labels)>
<!ELEMENT formname (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT labels (label+)>
<!ELEMENT label (program_name, original_text, client_text, label_description, client_label_description, program_type*, tooltip* ,SQL_variable_type*, SQL_column_name*, SQL_table*, associated_control*, max_size*, max_value*, min_value*, alternate_text*, alternate_tooltip* )>
<!ELEMENT program_name (#PCDATA)>
<!ELEMENT original_text (#PCDATA)>
<!ELEMENT client_text (#PCDATA)>
<!ELEMENT label_description (#PCDATA)>
<!ELEMENT client_label_description (#PCDATA)>
<!ELEMENT program_type (#PCDATA)>
<!ELEMENT tooltip (#PCDATA)>
<!ELEMENT SQL_variable_type (#PCDATA)>
<!ELEMENT SQL_column_name (#PCDATA)>
<!ELEMENT SQL_table (#PCDATA)>
<!ELEMENT associated_control (#PCDATA)>
<!ELEMENT max_size (#PCDATA)>
<!ELEMENT max_value (#PCDATA)>
<!ELEMENT min_value (#PCDATA)>
<!ELEMENT alternate_text (#PCDATA)>
<!ELEMENT alternate_tooltip (#PCDATA)>

<!ATTLIST header type (Static|Dynamic) #REQUIRED>
<!ATTLIST product prod_id ID #REQUIRED>
<!ATTLIST form form_id ID #REQUIRED>
<!ATTLIST label label_id ID #REQUIRED>
<!ATTLIST label important (true|false) #REQUIRED>
<!ATTLIST label visible (true|false) #REQUIRED>

=== emospy/HR/XMLLabels/Penalties.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="XSLTableShortView.xsl"?>
<!DOCTYPE Labels_Description SYSTEM "DTDDoc.dtd">

<Labels_Description>
  <product prod_id="p1">
    <product_name>HR</product_name>
    <version>1.13</version>
    <client_name>BIM</client_name>
    <forms>
      <form form_id="f3">
        <formname>tabPagePenalty</formname>
        <description>Тук се въвеждат наказанията за служителя</description>
        <header type="Static">Наказания</header>
        <labels>
          <label label_id="l1" important="false" visible="true">
            <program_name>groupBoxPenalty</program_name>
            <original_text>Данни за наказание</original_text>
            <client_text>Данни за наказание</client_text>
            <label_description></label_description>
            <client_label_description></client_label_description>
          </label>
          <label label_id="l2" important="false" visible="true">
            <program_name>labelPenaltyReason</program_name>
            <original_text>Основание :</original_text>
            <client_text>Основание :</client_text>
            <label_description>Основание за назначаване</label_description>
            <client_label_description></client_label_description>
            <tooltip>Основание за назначаване</tooltip>
            <associated_control>comboBoxPenaltyReason</associated_control>
          </label>
          <label label_id="l3" important="false" visible="true">
            <program_name>buttonPenaltyReason</program_name>
            <original_text></original_text>
            <client_text></client_text>
            <label_description>Бутон за извикване на номеклатура</label_description>
            <client_label_description></client_label_description>
            <tooltip>Номенклатура научно звание</tooltip>
          </label>
          <label label_id="l4" important="false" visible="true">
            <program_name>labelPenalty</program_name>
            <original_text>В сила от:</original_text>
            <client_text></client_text>
            <label_description>Дата от която е валидно наказанието</label_description>
            <client_label_description></client_label_description>
            <tooltip>В сила от</tooltip>
            <associated_control>dateTimePickerPenaltyDate</associated_control>
          </label>
          <label label_id="l5" important="false" visible="true">
            <program_name>label30</program_name>
            <original_text>Валидно до</original_text>
            <client_text></client_text>
            <label_description>Дата до която е валидно наказанието</label_description>
            <client_label_description></client_label_description>
            <tooltip>Валидно до</tooltip>
            <associated_control>dateTimePickerPenaltyTo</associated_control>
          </label>
          <label label_id="l6" important="false" visible="true">
            <program_name>label31</program_name>
            <original_text>Вид наказание:</original_text>
            <client_text></client_text>
            <label_description>Вид наказание:</label_description>
            <client_label_description></client_label_description>
            <tooltip>Вид наказание:</tooltip>
            <associated_control>comboBoxTypePenalty</associated_control>
          </label>
          <label label_id="l7" important="false" visible="true">
            <program_name>buttonTypePenalty</program_name>
            <original_text></original_text>
            <client_text></client_text>
            <label_description>Номенклатура вид наказание</label_description>
            <client_label_description></client_label_description>
            <tooltip>Номенклатура вид наказание</tooltip>
          </label>
          <label label_id="l8" important="false" visible="true">
            <program_name>label20</program_name>
            <original_text>Номер заповед :</original_text>
            <client_text>Номер заповед :</client_text>
            <label_description></label_description>
            <client_label_description></client_label_description>
            <tooltip>Номер заповед :</tooltip>
            <associated_control>numBoxPenaltyOrder</associated_control>
          </label>
          <label label_id="l9" important="false" visible="true">
            <program_name>label21</program_name>
            <original_text>От дата :</original_text>
            <client_text></client_text>
            <label_description>Дата на която влиза в сила заповедта</label_description>
            <client_label_description></client_label_description>
            <tooltip>Дата на която влиза в сила заповедта</tooltip>
            <associated_control>dateTimePenaltyFormDate</associated_control>
          </label>
          <label label_id="l10" important="false" visible="true">
            <program_name>groupBoxPenaltyGrid</program_name>
            <original_text>Данни за  наложени наказания за служителя</original_text>
            <client_text></client_text>
            <label_description>Данни за  наложени наказания за служителя</label_description>
            <client_label_description></client_label_description>
          </label>
        </labels>
      </form>
    </forms>
  </product>
</Labels_Description>

=== emospy/HR/XMLLabels/MainLabelDescription.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="XSLTableView.xsl"?>
<!DOCTYPE Labels_Description SYSTEM "DTDDoc.dtd">
<Labels_Description>
	<product prod_id = "p1">
		<product_name>HR</product_name>
		<version>1.13</version>
		<client_name>СКС</client_name>
		<forms>
			<form form_id = "f1">
				<formname>TabPersonalInfo</formname>
				<description>Тук се съхраняват всички данни от досието за всяко от лицата</description>
				<header type = "Static" >Лични данни</header>
				<labels>
          <label label_id = "l100" important="false" visible="true">
            <program_name></program_name>
            <original_text></original_text>
            <client_text></client_text>
            <label_description></label_description>
            <client_label_description></client_label_description>
            <program_type></program_type>
            <tooltip></tooltip>
            <SQL_variable_type></SQL_variable_type>
            <SQL_column_name></SQL_column_name>
            <SQL_table></SQL_table>
            <associated_control></associated_control>
            <max_size></max_size>
            <max_value></max_value>
            <min_value></min_value>
          </label>
					<label label_id = "l1" important="false" visible="true">
						<program_name>label1</program_name>
						<original_text>ЕГН:</original_text>
						<client_text>ЕГН:</client_text>
						<label_description>ЕГН на служител. Полето е ограничено да приема само цифри
							 и се прави контрол по първите 6 цифри (проверява се за коректна дата).
							 Също така трябва да се въведата точно 10 цифри.</label_description>
						<client_label_description>ЕГН на служител</client_label_description>
						<program_type>string</program_type>
						<tooltip> Тука се казва к'во трябва да се въвежда</tooltip>
						<SQL_variable_type>VARCHAR()</SQL_variable_type>
						<SQL_column_name>egn</SQL_column_name>
						<SQL_table>person</SQL_table>
						<associated_control>numBoxEgn</associated_control>
						<max_size>10</max_size>
						<max_value></max_value>
						<min_value></min_value>
					</label>
					<label label_id = "l2" important="false" visible="true">
						<program_name>labelNames</program_name>
						<original_text>Трите имена на лицето :</original_text>
						<client_text>Трите имена на лицето :</client_text>
						<label_description>Трите имена на лицето</label_description>
						<client_label_description>Трите имена на лицето</client_label_description>
						<SQL_variable_type>string</SQL_variable_type>
						<SQL_column_name>name</SQL_column_name>
						<associated_control>textBoxNames</associated_control>
						<max_size>255</max_size>
					</label>
					<label label_id = "l3" important="false" visible="true">
						<program_name>labelCountry</program_name>
						<original_text>Гражданство :</original_text>
						<client_text>Гражданство :</client_text>
						<label_description>Гражданство. По лична карта.</label_description>
						<client_label_description>Гражданство</client_label_description>
						<SQL_variable_type>string</SQL_variable_type>
						<SQL_column_name>Country</SQL_column_name>
						<associated_control>textBoxCountry</associated_control>
						<max_size>30</max_size>
					</label>
					<label label_id = "l4" important ="false" visible="true">
						<program_name>labelBornTown</program_name>
						<original_text>Месторождение град :</original_text> 
						<client_text>Месторождение град :</client_text>
						<label_description>Месторождение град : Това се преписва от личната карта.</label_description>
						<client_label_description>Месторождение град :</client_label_description>
						<SQL_variable_type>string</SQL_variable_type>
						<SQL_column_name>borntown</SQL_column_name>
						<associated_control>textBoxBornTown</associated_control>
						<max_size>50</max_size>						
					</label>
				</labels>
			</form>
		</forms>
	</product>
</Labels_Description>

=== emospy/HR/XMLLabels/DlHak.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="XSLColourView.xsl"?>
<!DOCTYPE Labels_Description SYSTEM "DTDDoc.dtd">
<Labels_Description>
  <product prod_id = "p1">
    <product_name>HR</product_name>
    <version>1.13</version>
    <client_name>СКС</client_name>
    <forms>
      <form form_id = "f1">
        <formname>formCharacteristic</formname>
        <description>Тук се съхраняват всички данни за длъжностната характеристика</description>
        <header type = "Static" >Длъжностна характеристика</header>
        <labels>
          <label label_id = "l1" important="false" visible="true">
            <program_name>label1</program_name>
            <original_text>НКП</original_text>
            <client_text>НКП</client_text>
            <label_description>
              Код по НКП
            </label_description>
            <client_label_description>Код по НКП</client_label_description>
            <program_type>string</program_type>
            <tooltip> Код по НКП</tooltip>
            <SQL_variable_type>VARCHAR()</SQL_variable_type>
            <SQL_column_name>nkpcode</SQL_column_name>
            <SQL_table>firmpersonal</SQL_table>
            <associated_control>textboxNkpCode</associated_control>
            <max_size>12</max_size>
            <max_value></max_value>
            <min_value></min_value>
          </label>
          <label label_id = "l2" important="true" visible="true">
            <program_name>labelNames</program_name>
            <original_text>Трите имена на лицето :</original_text>
            <client_text>Трите имена на лицето :</client_text>
            <label_description>Трите имена на лицето</label_description>
            <client_label_description>Трите имена на лицето</client_label_description>
            <SQL_variable_type>string</SQL_variable_type>
            <SQL_column_name>name</SQL_column_name>
            <associated_control>textBoxNames</associated_control>
            <max_size>255</max_size>
          </label>
          <label label_id = "l3" important="true" visible="true">
            <program_name>labelCountry</program_name>
            <original_text>Гражданство :</original_text>
            <client_text>Гражданство :</client_text>
            <label_description>Гражданство. По лична карта.</label_description>
            <client_label_description>Гражданство</client_label_description>
            <SQL_variable_type>string</SQL_variable_type>
            <SQL_column_name>Country</SQL_column_name>
            <associated_control>textBoxCountry</associated_control>
            <max_size></max_size>
          </label>
          <label label_id = "l4" important ="false" visible="true">
            <program_name>labelBornTown</program_name>
            <original_text>Месторождение град :</original_text>
            <client_text>Месторождение град :</client_text>
            <label_description>Месторождение град : Това се преписва от личната карта.</label_description>
            <client_label_description>Месторождение град :</client_label_description>
            <SQL_variable_type>string</SQL_variable_type>
            <SQL_column_name>borntown</SQL_column_name>
            <associated_control>textBoxBornTown</associated_control>
            <max_size></max_size>
          </label>
        </labels>
      </form>
    </forms>
  </product>
</Labels_Description>
