=== emospy/HR/XMLLabels/HRLabels/Shumen/ExcelDTD.dtd
<!ELEMENT Excel_Template_Description (template)>
<!ELEMENT template (template_name, client_name, data_views)>
<!ELEMENT template_name (#PCDATA)>
<!ELEMENT client_name (#PCDATA)>
<!ELEMENT data_views (vuePositions*, vuePerson*)>
<!ELEMENT vuePositions (#PCDATA)>
<!ELEMENT vuePerson (#PCDATA)>

<!--
<!ELEMENT vueAssignment (#PCDATA)>
<!ELEMENT vueHoliday (#PCDATA)>
<!ELEMENT vueAttestations (#PCDATA)> 
-->
<!ATTLIST vuePositions id ID #REQUIRED>
<!ATTLIST vuePositions column_text CDATA #REQUIRED>
<!ATTLIST vuePositions column_number CDATA #REQUIRED>

<!ATTLIST vuePerson id ID #REQUIRED>
<!ATTLIST vuePerson column_text CDATA #REQUIRED>
<!ATTLIST vuePerson column_number CDATA #REQUIRED>

<!--
<!ATTLIST vueAssignment id ID #REQUIRED>
<!ATTLIST vueAssignments column_text CDATA #REQUIRED>
<!ATTLIST vueAssignments column_number CDATA #REQUIRED>

<!ATTLIST vueHoliday id ID #REQUIRED>
<!ATTLIST vueHoliday column_text CDATA #REQUIRED>
<!ATTLIST vueHoliday column_number CDATA #REQUIRED>

<!ATTLIST vueAttestations id ID #REQUIRED>
<!ATTLIST vueAttestations column_text CDATA #REQUIRED>
<!ATTLIST vueAttestations column_number CDATA #REQUIRED> -->


<!-- <!ELEMENT Excel_Template_Description (template)>
<!ELEMENT template (template_name, client_name, data_views)>
<!ELEMENT template_name (#PCDATA)>
<!ELEMENT client_name (#PCDATA)>
<!ELEMENT data_views (data_view)>
<!ELEMENT data_view (view_name, column_count, columns)>
<!ELEMENT view_name (#PCDATA)>
<!ELEMENT column_count (#PCDATA)>
<!ELEMENT columns (column+)>
<!ELEMENT column (column_number, column_text)>
<!ELEMENT column_number (#PCDATA)>
<!ELEMENT column_text (#PCDATA)> -->

=== emospy/HR/XMLLabels/HRLabels/Shumen/OSR.xml
<?xml version="1.0"?>
<!DOCTYPE Excel_Template_Description SYSTEM "ExcelDTD.dtd">
<Excel_Template_Description>
  <template>
    <template_name>OSR</template_name>
    <client_name>Shumen University</client_name>
    <data_views>
      <vuePositions id="v1" column_number="2" column_text="nameOfPosition"></vuePositions>
      <vuePositions id="v2" column_number="3" column_text="Education"></vuePositions>
      <vuePositions id="v3" column_number="4" column_text="otherRequirements"></vuePositions>
      <vuePositions id="v4" column_number="5" column_text="staffCount"></vuePositions>
      <vuePositions id="v6" column_number="6" column_text="NKPCode"></vuePositions>
      <vuePositions id="v7" column_number="7" column_text="StartSalary"></vuePositions>
      <vuePositions id="v8" column_number="8" column_text="BaseSalary"></vuePositions>
      <vuePositions id="v9" column_number="9" column_text="SalaryAddon"></vuePositions>
      <vuePositions id="v10" column_number="10" column_text="ScienceAddon"></vuePositions>
      <vuePositions id="v11" column_number="11" column_text="OtherAddon"></vuePositions>
    </data_views>
  </template>
</Excel_Template_Description>

=== emospy/HR/XMLLabels/HRLabels/Shumen/PSR.xml
<?xml version="1.0"?>
<!DOCTYPE Excel_Template_Description SYSTEM "ExcelDTD.dtd">
<Excel_Template_Description>
  <template>
    <template_name>OSR</template_name>
    <client_name>Shumen University</client_name>
    <data_views>
      <vuePositions id="v2" column_number="6" column_text="Education"></vuePositions>
      <vuePositions id="v4" column_number="7" column_text="Experience"></vuePositions>
      <vuePositions id="v5" column_number="10" column_text="staffcount"></vuePositions>
      <vuePositions id="v9" column_number="13" column_text="NKPCode"></vuePositions>
      <vuePositions id="v10" column_number="14" column_text="MinSalary"></vuePositions>
      <vuePositions id="v11" column_number="15" column_text="MaxSalary"></vuePositions>
      <vuePerson id="v12" column_number="4" column_text="name"></vuePerson>
      <vuePerson id="v13" column_number="5" column_text="egn"></vuePerson>
      <vuePerson id="v19" column_number="8" column_text="education"></vuePerson>
      <vuePerson id="v20" column_number="9" column_text="sciencelevel"></vuePerson>
      <vuePerson id="v21" column_number="16" column_text="basesalary"></vuePerson>
      <vuePerson id="v22" column_number="17" column_text="salaryaddon"></vuePerson>
      <vuePerson id="v14" column_number="18" column_text="cyears"></vuePerson>
      <vuePerson id="v15" column_number="19" column_text="cyears"></vuePerson>
      <vuePerson id="v16" column_number="20" column_text="shumenclasssalary"></vuePerson>
      <vuePerson id="v17" column_number="21" column_text="monthlyaddon"></vuePerson>
      <vuePerson id="v18" column_number="22" column_text="yearlyaddon"></vuePerson>
      <vuePerson id="v19" column_number="23" column_text="shumentotalsalary"></vuePerson>
    </data_views>
  </template>
</Excel_Template_Description>
